"""Migrations and database hardening on a real PostgreSQL server.

Runs only when ``AEGIS_TEST_DATABASE_URL`` points at PostgreSQL through a role that may create
roles (a disposable test cluster). The test rebuilds the production layout - a non-superuser
*owner* role that runs the migrations and a *runtime* role for the application - and proves:

* ``alembic upgrade head`` needs no superuser rights, and the models match the migrations
  (``alembic check`` finds no drift);
* the runtime role can read and write application data but cannot change the schema, rewrite or
  delete the audit trail, or move ``alembic_version``;
* not even the owner can UPDATE, DELETE or TRUNCATE the audit trail (trigger);
* the downgrade path works and the schema can be rebuilt afterwards.
"""

from __future__ import annotations

import asyncio
import secrets
from collections.abc import Iterator
from dataclasses import dataclass

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import URL, make_url, text
from sqlalchemy.exc import DBAPIError
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.pool import NullPool

from tests.conftest import ROOT, TEST_DATABASE_URL

pytestmark = [
    pytest.mark.postgres,
    pytest.mark.skipif(
        not (TEST_DATABASE_URL or "").startswith("postgresql"),
        reason="set AEGIS_TEST_DATABASE_URL to a PostgreSQL database",
    ),
]


def _quote(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


async def _execute(url: URL, *statements: str) -> list[object]:
    """Run statements in one transaction; returns the first column of each result's first row."""
    engine = create_async_engine(url, poolclass=NullPool)
    try:
        async with engine.begin() as connection:
            results: list[object] = []
            for statement in statements:
                result = await connection.execute(text(statement))
                results.append(result.scalar() if result.returns_rows else None)
            return results
    finally:
        await engine.dispose()


def run(url: URL, *statements: str) -> list[object]:
    return asyncio.run(_execute(url, *statements))


def refused(url: URL, statement: str, match: str) -> None:
    with pytest.raises(DBAPIError, match=match):
        run(url, statement)


@dataclass(frozen=True)
class Layout:
    admin: URL
    owner: URL
    app: URL
    app_role: str


@pytest.fixture
def layout(monkeypatch: pytest.MonkeyPatch) -> Iterator[Layout]:
    admin = make_url(TEST_DATABASE_URL or "")
    (allowed,) = run(
        admin, "SELECT rolsuper OR rolcreaterole FROM pg_roles WHERE rolname = current_user"
    )
    if not allowed:
        pytest.skip("the test database role cannot create roles")

    suffix = secrets.token_hex(4)
    owner_role, app_role = f"aegis_t_owner_{suffix}", f"aegis_t_app_{suffix}"
    owner_password, app_password = secrets.token_hex(16), secrets.token_hex(16)
    database = _quote(admin.database or "")
    run(
        admin,
        "DROP SCHEMA IF EXISTS public CASCADE",
        f"CREATE ROLE {owner_role} LOGIN PASSWORD '{owner_password}' "
        "NOSUPERUSER NOCREATEDB NOCREATEROLE",
        f"CREATE ROLE {app_role} LOGIN PASSWORD '{app_password}' "
        "NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT",
        f"CREATE SCHEMA public AUTHORIZATION {owner_role}",
        f"GRANT CONNECT ON DATABASE {database} TO {owner_role}, {app_role}",
        f"GRANT USAGE ON SCHEMA public TO {app_role}",
    )
    owner = admin.set(username=owner_role, password=owner_password)
    app = admin.set(username=app_role, password=app_password)
    monkeypatch.setenv("AEGIS_MIGRATION_DATABASE_URL", owner.render_as_string(hide_password=False))
    monkeypatch.setenv("AEGIS_DB_APP_ROLE", app_role)
    try:
        yield Layout(admin=admin, owner=owner, app=app, app_role=app_role)
    finally:
        run(
            admin,
            "DROP SCHEMA IF EXISTS public CASCADE",
            "CREATE SCHEMA public",
            f"DROP OWNED BY {app_role}, {owner_role}",
            f"DROP ROLE {app_role}",
            f"DROP ROLE {owner_role}",
        )


def alembic_config() -> Config:
    # No ini file: the migration environment then leaves the test process' logging alone.
    config = Config()
    config.set_main_option("script_location", str(ROOT / "migrations"))
    return config


AUDIT_INSERT = (
    "INSERT INTO audit_events (id, occurred_at, action, outcome, details) "
    "VALUES (gen_random_uuid(), now(), 'probe', 'success', '{}')"
)


def test_migrations_build_a_hardened_schema(layout: Layout) -> None:
    config = alembic_config()
    command.upgrade(config, "head")
    command.check(config)  # raises AutogenerateDiffsDetected if models and migrations differ

    # The runtime role works with data (also in the tables of later revisions) ...
    assert run(layout.app, "SELECT count(*) FROM users") == [0]
    assert run(layout.app, "SELECT count(*) FROM mfa_challenges") == [0]
    assert run(layout.app, "SELECT count(*) FROM mfa_recovery_codes") == [0]
    run(layout.app, AUDIT_INSERT)
    assert run(layout.app, "SELECT count(*) FROM audit_events") == [1]
    # ... but cannot rewrite history or change the schema.
    for statement in (
        "UPDATE audit_events SET action = 'tampered'",
        "DELETE FROM audit_events",
        "TRUNCATE audit_events",
        "UPDATE alembic_version SET version_num = '0001'",
    ):
        refused(layout.app, statement, "permission denied")
    refused(layout.app, "CREATE TABLE intruder (id int)", "permission denied for schema public")
    refused(layout.app, "DROP TABLE users", "must be owner")
    refused(layout.app, "ALTER TABLE users ADD COLUMN intruder int", "must be owner")

    # Not even the owner can change the audit trail while the trigger is in place.
    for statement in (
        "UPDATE audit_events SET action = 'tampered'",
        "DELETE FROM audit_events",
        "TRUNCATE audit_events",
    ):
        refused(layout.owner, statement, "append-only")
    assert run(layout.admin, "SELECT count(*) FROM audit_events") == [1]

    # The downgrade path works and the schema can be rebuilt.
    command.downgrade(config, "base")
    assert run(layout.admin, "SELECT to_regclass('public.users') IS NULL") == [True]
    command.upgrade(config, "head")
    assert run(layout.admin, "SELECT version_num FROM alembic_version") == ["0003"]
