"""Generate the reference documentation from the code (the code is the single source of truth).

    python scripts/generate_docs.py            # rewrite the generated documents
    python scripts/generate_docs.py --check    # exit 1 if any of them is out of date (tests/CI)

Generated documents:

* docs/configuration.md  - every setting, from ``aegis.core.config.Settings``
* docs/api-reference.md  - every route, with the permission its dependencies enforce, the rate
                            limits its handler applies and the RBAC matrix
* docs/tools.md          - the tools the model may call and the intents that allow them
"""

from __future__ import annotations

import enum
import inspect
import re
import sys
import types
import typing
from collections.abc import Callable, Iterator
from pathlib import Path
from typing import Any

import annotated_types
from fastapi.dependencies.models import Dependant
from fastapi.routing import APIRoute
from pydantic import SecretStr, StringConstraints
from pydantic_core import PydanticUndefined

# Run inside the project environment (`uv sync` installs the `aegis` package).
from aegis.agents.intents import IntentRegistry
from aegis.api import deps
from aegis.api.health import router as health_router
from aegis.api.router import API_V1_PREFIX, V1_DEPENDENCIES, V1_ROUTERS
from aegis.core.config import Settings
from aegis.domain.enums import Role
from aegis.security.rbac import ROLE_PERMISSIONS, Permission
from aegis.tools.catalog import TOOLS

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
GENERATED_NOTE = "<!-- Generated by scripts/generate_docs.py - do not edit by hand. -->"


# =================================================================================================
# docs/configuration.md
# =================================================================================================
CONFIG_GROUPS: list[tuple[str, tuple[str, ...]]] = [
    (
        "Application",
        (
            "env",
            "app_name",
            "log_level",
            "log_json",
            "api_docs_enabled",
            "company_name",
            "help_center_url",
        ),
    ),
    (
        "HTTP server",
        (
            "allowed_hosts",
            "cors_origins",
            "trusted_proxies",
            "max_request_body_bytes",
            "max_upload_bytes",
            "hsts_enabled",
        ),
    ),
    ("Database", ("database_",)),
    ("Redis", ("redis_",)),
    (
        "Authentication and cryptography",
        (
            "jwt_",
            "access_token",
            "refresh_token",
            "session_",
            "field_encryption",
            "password_",
            "login_",
            "argon2_",
            "metrics_token",
            "mfa_",
        ),
    ),
    ("Rate limits", ("rl_",)),
    ("Language model", ("llm_", "anthropic_")),
    ("Agent", ("agent_",)),
    ("Retrieval (RAG)", ("qdrant_", "embedding_", "voyage_", "rag_")),
    ("E-mail", ("email_", "mailbox_", "smtp_")),
    ("Payments", ("payment_", "stripe_")),
    ("Privacy", ("conversation_retention",)),
    ("Worker", ("worker_",)),
    ("Miscellaneous", ("metrics_enabled", "idempotency_")),
]


def _default(field: Any) -> str:
    if field.default is PydanticUndefined and field.default_factory is None:
        return "**required**"
    value = field.default_factory() if field.default_factory is not None else field.default
    if isinstance(value, SecretStr):
        return "(secret)"
    if isinstance(value, list):
        return ", ".join(str(v) for v in value) or "(empty)"
    if value is None:
        return "(unset)"
    return str(getattr(value, "value", value))


def _type_hint(annotation: Any) -> str:
    args = [a for a in typing.get_args(annotation) if a is not type(None)]
    if typing.get_origin(annotation) is typing.Literal:
        return " / ".join(f"`{a}`" for a in typing.get_args(annotation))
    if isinstance(annotation, type) and issubclass(annotation, enum.Enum):
        return " / ".join(f"`{m.value}`" for m in annotation)
    if annotation is SecretStr or SecretStr in args:
        return "secret"
    if typing.get_origin(annotation) is list or any(typing.get_origin(a) is list for a in args):
        return "comma-separated list"
    for arg in args:
        hint = _type_hint(arg)
        if hint:
            return hint
    return ""


def _bounds(metadata: list[Any]) -> list[str]:
    parts: list[str] = []
    for meta in metadata:
        if isinstance(meta, annotated_types.Ge):
            parts.append(f">= {meta.ge}")
        elif isinstance(meta, annotated_types.Gt):
            parts.append(f"> {meta.gt}")
        elif isinstance(meta, annotated_types.Le):
            parts.append(f"<= {meta.le}")
        elif isinstance(meta, annotated_types.Lt):
            parts.append(f"< {meta.lt}")
        elif isinstance(meta, annotated_types.MinLen):
            parts.append(f"min length {meta.min_length}")
        elif isinstance(meta, annotated_types.MaxLen):
            parts.append(f"max length {meta.max_length}")
        elif isinstance(meta, StringConstraints):
            if meta.min_length is not None:
                parts.append(f"min length {meta.min_length}")
            if meta.max_length is not None:
                parts.append(f"max length {meta.max_length}")
            if meta.pattern is not None:
                parts.append(f"pattern `{meta.pattern}`")
        elif getattr(meta, "pattern", None):
            parts.append(f"pattern `{meta.pattern}`")
    return parts


def _matches(name: str, prefixes: tuple[str, ...]) -> bool:
    return any(name == p or name.startswith(p) for p in prefixes)


def render_configuration() -> str:
    fields = dict(Settings.model_fields)
    undocumented = [name for name, field in fields.items() if not field.description]
    if undocumented:
        msg = f"settings without a docstring: {undocumented}"
        raise SystemExit(msg)
    lines = [
        "# Configuration reference",
        "",
        GENERATED_NOTE,
        "",
        "Every setting is read from an environment variable named `AEGIS_<NAME>` (upper case), or from a",
        "`.env` file in development. Secrets are typed as `SecretStr`: they never appear in logs, `repr()` or",
        "validation errors. With `AEGIS_ENV=production` the process refuses to start with unsafe values",
        "(SQLite, no Redis, embedded vector index, wildcard hosts/CORS, development mailbox, no metrics",
        "token, HSTS off, DEBUG or non-JSON logging, optional staff two-factor authentication, the",
        "simulated payment provider, placeholder secrets).",
        "",
        "An empty variable (`AEGIS_METRICS_TOKEN=`) means *unset* - the default applies - so an empty value can",
        "never become a valid credential. In production, secrets can also be mounted as files: set",
        "`AEGIS_SECRETS_DIR` to a directory holding one file per variable (`AEGIS_JWT_SECRET`,",
        "`AEGIS_DATABASE_URL`, ...); environment variables take precedence over `.env`, which takes",
        "precedence over secret files.",
        "",
        "Additional variables read outside the settings model: `AEGIS_SECRETS_DIR` (see above),",
        "`AEGIS_MIGRATION_DATABASE_URL` (schema-owner connection used by migrations), `AEGIS_DB_APP_ROLE`",
        "(runtime role granted by migration 0002), `AEGIS_BOOTSTRAP_ADMIN_PASSWORD` (non-interactive",
        "`aegis create-admin`), `AEGIS_TEST_DATABASE_URL` (run the test suite on PostgreSQL). The Docker",
        "Compose file additionally reads `POSTGRES_PASSWORD`, `AEGIS_DB_OWNER_PASSWORD`,",
        "`AEGIS_DB_APP_PASSWORD`, `REDIS_PASSWORD` and `QDRANT_API_KEY` (created by `aegis init-env --docker`).",
        "",
    ]
    used: set[str] = set()
    for title, prefixes in CONFIG_GROUPS:
        names = [n for n in fields if n not in used and _matches(n, prefixes)]
        if not names:
            continue
        used.update(names)
        lines += [
            f"## {title}",
            "",
            "| Variable | Meaning | Default | Constraints |",
            "|---|---|---|---|",
        ]
        for name in names:
            field = fields[name]
            constraints = ", ".join(
                p for p in (_type_hint(field.annotation), *_bounds(field.metadata)) if p
            )
            lines.append(
                f"| `AEGIS_{name.upper()}` | {field.description} | {_default(field)} "
                f"| {constraints or '-'} |"
            )
        lines.append("")
    leftovers = [n for n in fields if n not in used]
    if leftovers:
        msg = f"settings not assigned to a documentation group: {leftovers}"
        raise SystemExit(msg)
    return "\n".join(lines).rstrip() + "\n"


# =================================================================================================
# docs/api-reference.md
# =================================================================================================
_RATE_LIMIT_PATTERN = re.compile(r"rate_limits\.(\w+)")


def _walk(dependant: Dependant) -> Iterator[Dependant]:
    for child in dependant.dependencies:
        yield child
        yield from _walk(child)


def _type_name(annotation: Any) -> str:
    if annotation is None:
        return "-"
    if isinstance(annotation, type) and not typing.get_args(annotation):
        return f"`{annotation.__name__}`"
    # "aegis.schemas.common.Page[aegis.schemas.admin.UserOut]" -> "Page[UserOut]"
    text = re.sub(r"\b[\w.]+\.(\w+)", r"\1", repr(annotation).replace("typing.", ""))
    # A "|" must be escaped inside a table cell, even within a code span (GFM).
    return "`" + text.replace("|", "\\|") + "`"


def _is_ours(func: Callable[..., Any]) -> bool:
    return str(getattr(func, "__module__", "")).startswith("aegis.")


def _limits_in(func: Callable[..., Any]) -> list[str]:
    try:
        return _RATE_LIMIT_PATTERN.findall(inspect.getsource(func))
    except (OSError, TypeError):
        return []


def _route_facts(route: APIRoute, *, versioned: bool) -> dict[str, str]:
    dependants = list(_walk(route.dependant))
    calls = [d.call for d in dependants if d.call is not None]
    if versioned:
        calls += [d.dependency for d in V1_DEPENDENCIES if d.dependency is not None]
    requirements = [r for r in (deps.requirement_of(c) for c in calls) if r is not None]
    authenticated = deps.get_principal in calls
    if requirements:
        access = ", ".join(f"`{r.permission.value}`" for r in requirements)
    elif authenticated:
        access = "authenticated ¹"
    else:
        access = "public"

    limits: list[str] = ["api_ip"] if deps.ip_rate_limit in calls else []
    limits += _limits_in(route.endpoint)
    # Limits applied by the route's own helper dependencies (e.g. the MFA management budget).
    shared = {deps.get_principal, deps.ip_rate_limit}
    for call in calls:
        if call not in shared and deps.requirement_of(call) is None and _is_ours(call):
            limits += _limits_in(call)
    if authenticated:
        limits.append("api_user")
    if any(r.admin_rate_limit for r in requirements):
        limits.append("admin")

    headers = {param.alias for d in (route.dependant, *dependants) for param in d.header_params}
    body = route.dependant.body_params
    body_text = "-"
    if body:
        annotation = body[0].field_info.annotation
        body_text = _type_name(annotation)
        if "multipart" in repr(body[0].field_info).lower() or len(body) > 1:
            body_text = "multipart form"
    status = route.status_code or 200
    response = _type_name(route.response_model) if route.response_model else "-"
    notes = []
    if "Idempotency-Key" in headers:
        notes.append("`Idempotency-Key`")
    query = [p.alias for p in route.dependant.query_params]
    if query:
        notes.append("query: " + ", ".join(f"`{q}`" for q in query))
    return {
        "access": access,
        "limits": ", ".join(f"`{name}`" for name in dict.fromkeys(limits)) or "-",
        "body": body_text,
        "response": f"{status} {response}".strip(),
        "notes": "; ".join(notes) or "-",
    }


def _routes() -> list[tuple[str, APIRoute]]:
    """(full path, route) for every documented route, in registration order."""
    found = [*health_router.routes, *(route for router in V1_ROUTERS for route in router.routes)]
    return [
        (route.path, route)
        for route in found
        if isinstance(route, APIRoute) and route.include_in_schema
    ]


def render_api_reference() -> str:
    lines = [
        "# API reference",
        "",
        GENERATED_NOTE,
        "",
        "All endpoints live under `/api/v1` except the health probes. Conventions (authentication,",
        "errors, pagination, idempotency, rate limits) are described in [api.md](api.md); the full",
        "request and response schemas are served at `/docs` when the API documentation is enabled",
        "(`AEGIS_API_DOCS_ENABLED`, on by default outside production).",
        "",
        "**Access** lists the permission the route's dependencies enforce before the handler runs.",
        "¹ *authenticated*: any signed-in role may call the route; the service layer then decides",
        "per record (customers see only their own records - anything else is reported as *not found*;",
        "staff need the matching `*_any` permission). **Rate limits** are the policies the route",
        "applies (see `AEGIS_RL_*` in [configuration.md](configuration.md)); `/metrics` is described",
        "in [operations.md](operations.md).",
        "",
    ]
    by_tag: dict[str, list[tuple[str, APIRoute]]] = {}
    for path, route in _routes():
        tag = str(route.tags[0]) if route.tags else "other"
        by_tag.setdefault(tag, []).append((path, route))
    for tag, routes in by_tag.items():
        lines += [
            f"## {tag.capitalize()}",
            "",
            "| Method | Path | Access | Rate limits | Body | Response | Notes |",
            "|---|---|---|---|---|---|---|",
        ]
        for path, route in routes:
            facts = _route_facts(route, versioned=path.startswith(API_V1_PREFIX))
            for method in sorted(route.methods or ()):
                lines.append(
                    f"| {method} | `{path}` | {facts['access']} | {facts['limits']} "
                    f"| {facts['body']} | {facts['response']} | {facts['notes']} |"
                )
        lines.append("")

    roles = list(Role)
    lines += [
        "## Role permissions (RBAC matrix)",
        "",
        "| Permission | " + " | ".join(r.value for r in roles) + " |",
        "|---|" + "---|" * len(roles),
    ]
    for permission in Permission:
        marks = ["yes" if permission in ROLE_PERMISSIONS[r] else "" for r in roles]
        lines.append(f"| `{permission.value}` | " + " | ".join(marks) + " |")
    return "\n".join(lines).rstrip() + "\n"


# =================================================================================================
# docs/tools.md
# =================================================================================================
def _nested_metadata(annotation: Any) -> list[Any]:
    """Constraints declared inside ``Annotated[...]``, also within ``X | None``."""
    if typing.get_origin(annotation) is typing.Annotated:
        return list(annotation.__metadata__)
    return [m for arg in typing.get_args(annotation) for m in _nested_metadata(arg)]


def _parameter_type(annotation: Any) -> str:
    args = typing.get_args(annotation)
    origin = typing.get_origin(annotation)
    if origin is typing.Annotated:
        return _parameter_type(args[0])
    if origin in (typing.Union, types.UnionType):
        text = " or ".join(_parameter_type(a) for a in args if a is not type(None))
        return f"{text} or null" if type(None) in args else text
    if origin is typing.Literal:
        return "one of " + ", ".join(f"`{a}`" for a in args)
    if isinstance(annotation, type) and issubclass(annotation, enum.Enum):
        return "one of " + ", ".join(f"`{m.value}`" for m in annotation)
    return _type_name(annotation).strip("`")


def _parameter_rows(model: type[Any]) -> list[str]:
    rows = []
    for name, field in model.model_fields.items():
        metadata = [*field.metadata, *_nested_metadata(field.annotation)]
        constraints = ", ".join(dict.fromkeys(_bounds(metadata))) or "-"
        rows.append(
            f"| `{name}` | {_parameter_type(field.annotation)} | {constraints} "
            f"| {field.description or '-'} |"
        )
    return rows


def render_tools() -> str:
    registry = IntentRegistry.load_default(known_tools=frozenset(t.name for t in TOOLS))
    allowed_by: dict[str, list[str]] = {}
    for intent in registry.all():
        for tool in intent.tools:
            allowed_by.setdefault(tool, []).append(intent.name)
    lines = [
        "# Tools and intents",
        "",
        GENERATED_NOTE,
        "",
        "The model never touches the database or the network directly. It can only *request* one of",
        "the tools below; the executor ([agent.md](agent.md#6-tool-execution)) then checks the intent's",
        "allow-list, the per-turn budgets, the argument schema and the caller's permission before the",
        "handler runs - and every handler goes through the same services (and ownership checks) as the",
        "REST API. Side effects: **read** (no change), **write** (low-risk, audited),",
        "**propose** (creates a pending action the customer must confirm through the API - the model",
        "can never complete a refund or cancellation on its own), **escalate** (hands over to a human).",
        "",
        "## Tools",
        "",
    ]
    for tool in TOOLS:
        intents = ", ".join(f"`{name}`" for name in allowed_by.get(tool.name, [])) or "-"
        lines += [
            f"### `{tool.name}`",
            "",
            tool.description,
            "",
            f"- Side effect: **{tool.side_effect.value}**",
            f"- Permission: `{tool.permission.value}`",
            f"- Calls per turn: at most {tool.max_calls_per_turn}",
            f"- Allowed for intents: {intents}",
            "",
            "| Parameter | Type | Constraints | Description |",
            "|---|---|---|---|",
            *_parameter_rows(tool.input_model),
            "",
        ]
    lines += [
        "## Intents",
        "",
        "Defined in `src/aegis/agents/intents.toml` and validated at start-up.",
        "",
        "| Intent | Description | Default priority | Knowledge searched | Always escalates |",
        "|---|---|---|---|---|",
    ]
    for intent in registry.all():
        knowledge = ", ".join(f"`{k.value}`" for k in intent.knowledge) or "-"
        lines.append(
            f"| `{intent.name}` | {intent.description} | {intent.default_priority.value} "
            f"| {knowledge} | {'yes' if intent.always_escalate else 'no'} |"
        )
    return "\n".join(lines).rstrip() + "\n"


# =================================================================================================
TARGETS: dict[str, Callable[[], str]] = {
    "configuration.md": render_configuration,
    "api-reference.md": render_api_reference,
    "tools.md": render_tools,
}


def render_all() -> dict[Path, str]:
    return {DOCS / name: render() for name, render in TARGETS.items()}


def main() -> int:
    documents = render_all()
    if "--check" in sys.argv:
        stale = [
            path.name
            for path, content in documents.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print(f"out of date: {', '.join(stale)}; run python scripts/generate_docs.py")
            return 1
        return 0
    DOCS.mkdir(parents=True, exist_ok=True)
    for path, content in documents.items():
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote docs/{path.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
