"""Command-line interface: ``aegis <command>``.

Commands
    serve               run the API (uvicorn, no server header, proxy headers off by default)
    worker              run the background worker (indexing + housekeeping)
    migrate             apply database migrations (alembic upgrade head)
    seed                load the fictional demo business (development only)
    index-kb            index pending knowledge-base documents once (--rebuild: into an empty collection)
    create-admin        create an administrator (password prompted, never echoed)
    generate-secrets    print fresh random secrets for the environment
    init-env            write a .env with fresh secrets: development (default) or --docker
    rotate-encryption   re-encrypt encrypted columns with the newest key
    check-config        validate the configuration and print a redacted summary
    healthcheck         container health probe for the API (or --worker)
"""

from __future__ import annotations

import argparse
import asyncio
import getpass
import os
import secrets
import sys
import time
from pathlib import Path
from typing import Any

from aegis.core.config import Settings, load_settings
from aegis.security.crypto import generate_fernet_key

ENV_TEMPLATE = """# Generated by `aegis init-env` for LOCAL DEVELOPMENT. Never commit this file.
AEGIS_ENV=development
AEGIS_LOG_JSON=false
AEGIS_JWT_SECRET={jwt}
AEGIS_FIELD_ENCRYPTION_KEYS={fernet}
AEGIS_METRICS_TOKEN={metrics}
AEGIS_DATABASE_URL=sqlite+aiosqlite:///./var/aegis.db
AEGIS_QDRANT_LOCATION=var/qdrant
# AEGIS_REDIS_URL=redis://aegis:<password>@localhost:6379/0
# To use Claude instead of the offline model:
# AEGIS_LLM_PROVIDER=anthropic
# AEGIS_ANTHROPIC_API_KEY=...
"""


DOCKER_ENV_TEMPLATE = """# Generated by `aegis init-env --docker` for docker-compose.yml. Never commit this file.
# Compose reads these values and hands each container only the ones it needs: the API and the
# worker never see POSTGRES_PASSWORD or AEGIS_DB_OWNER_PASSWORD.
AEGIS_ENV=staging
AEGIS_JWT_SECRET={jwt}
AEGIS_FIELD_ENCRYPTION_KEYS={fernet}
AEGIS_METRICS_TOKEN={metrics}
POSTGRES_PASSWORD={postgres}
AEGIS_DB_OWNER_PASSWORD={owner}
AEGIS_DB_APP_PASSWORD={app}
REDIS_PASSWORD={redis}
QDRANT_API_KEY={qdrant}
# AEGIS_ALLOWED_HOSTS=support.example.com
# AEGIS_LLM_PROVIDER=anthropic
# AEGIS_ANTHROPIC_API_KEY=...
"""


def _secrets() -> dict[str, str]:
    """Fresh random values. URL-safe characters only, so they can be embedded in URLs."""
    return {
        "jwt": secrets.token_urlsafe(48),
        "fernet": generate_fernet_key(),
        "metrics": secrets.token_urlsafe(32),
        "postgres": secrets.token_urlsafe(24),
        "owner": secrets.token_urlsafe(24),
        "app": secrets.token_urlsafe(24),
        "redis": secrets.token_urlsafe(24),
        "qdrant": secrets.token_urlsafe(32),
    }


def cmd_generate_secrets(_: argparse.Namespace) -> int:
    values = _secrets()
    print(f"AEGIS_JWT_SECRET={values['jwt']}")
    print(f"AEGIS_FIELD_ENCRYPTION_KEYS={values['fernet']}")
    print(f"AEGIS_METRICS_TOKEN={values['metrics']}")
    print(f"POSTGRES_PASSWORD={values['postgres']}")
    print(f"AEGIS_DB_OWNER_PASSWORD={values['owner']}")
    print(f"AEGIS_DB_APP_PASSWORD={values['app']}")
    print(f"REDIS_PASSWORD={values['redis']}")
    print(f"QDRANT_API_KEY={values['qdrant']}")
    return 0


def cmd_init_env(args: argparse.Namespace) -> int:
    path = Path(args.path)
    if path.exists() and not args.force:
        print(f"{path} already exists; use --force to overwrite", file=sys.stderr)
        return 1
    template = DOCKER_ENV_TEMPLATE if args.docker else ENV_TEMPLATE
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(template.format(**_secrets()))
    if args.docker:
        print(f"wrote {path} (Docker Compose settings with fresh secrets)")
    else:
        Path("var").mkdir(exist_ok=True)
        print(f"wrote {path} (development settings with fresh secrets)")
    return 0


HEALTH_PATH = "/health/live"


def _health_host() -> str:
    """A Host header the API accepts: the first explicit entry of AEGIS_ALLOWED_HOSTS."""
    for host in os.environ.get("AEGIS_ALLOWED_HOSTS", "").split(","):
        candidate = host.strip()
        if candidate and "*" not in candidate:
            return candidate
    return "localhost"


def cmd_healthcheck(args: argparse.Namespace) -> int:
    """Exit 0 when healthy. Used by the container HEALTHCHECK; prints nothing on success."""
    if args.worker:
        path = os.environ.get("AEGIS_WORKER_HEARTBEAT_FILE", "").strip()
        if not path:
            print("AEGIS_WORKER_HEARTBEAT_FILE is not set", file=sys.stderr)
            return 1
        try:
            age = time.time() - Path(path).stat().st_mtime
        except OSError:
            print("no worker heartbeat yet", file=sys.stderr)
            return 1
        if age > args.max_age:
            print(f"worker heartbeat is {age:.0f}s old", file=sys.stderr)
            return 1
        return 0

    import httpx2  # noqa: PLC0415 - only needed for this command

    try:
        response = httpx2.get(
            f"http://127.0.0.1:{args.port}{HEALTH_PATH}",
            headers={"Host": _health_host()},
            timeout=3.0,
        )
    except httpx2.HTTPError as exc:
        print(f"health probe failed: {type(exc).__name__}", file=sys.stderr)
        return 1
    if response.status_code != 200:
        print(f"health probe returned HTTP {response.status_code}", file=sys.stderr)
        return 1
    return 0


def cmd_check_config(_: argparse.Namespace) -> int:
    settings = load_settings()
    print(f"environment:      {settings.env.value}")
    print(f"database:         {'sqlite' if settings.is_sqlite else 'postgresql'}")
    print(f"redis:            {'configured' if settings.redis_url else 'in-process (dev only)'}")
    print(
        f"vector store:     {'server' if settings.qdrant_url else f'embedded ({settings.qdrant_location})'}"
    )
    print(f"llm provider:     {settings.llm_provider.value}")
    print(f"embeddings:       {settings.embedding_provider.value}")
    print(f"docs enabled:     {settings.docs_enabled}")
    print("secrets:          present (values hidden)")
    return 0


def cmd_serve(args: argparse.Namespace) -> int:
    import uvicorn  # noqa: PLC0415 - only needed for this command

    uvicorn.run(
        "aegis.main:create_app",
        factory=True,
        host=args.host,
        port=args.port,
        server_header=False,
        proxy_headers=False,
        access_log=False,
        log_level="warning",
    )
    return 0


def cmd_worker(args: argparse.Namespace) -> int:
    from aegis.workers.runner import run_worker  # noqa: PLC0415

    settings = load_settings()
    _configure_logging(settings)
    asyncio.run(run_worker(settings, once=args.once))
    return 0


def cmd_migrate(_: argparse.Namespace) -> int:
    from alembic import command  # noqa: PLC0415
    from alembic.config import Config  # noqa: PLC0415

    config = Config(str(Path(__file__).resolve().parents[2] / "alembic.ini"))
    if not Path(config.config_file_name or "").exists():
        config = Config("alembic.ini")
    command.upgrade(config, "head")
    return 0


def _configure_logging(settings: Settings) -> None:
    from aegis.observability.logging import configure_logging  # noqa: PLC0415

    configure_logging(level=settings.log_level, json_output=settings.log_json)


def cmd_seed(args: argparse.Namespace) -> int:
    from aegis.bootstrap import AppContainer  # noqa: PLC0415
    from aegis.seed import seed_demo_data  # noqa: PLC0415

    settings = load_settings()
    _configure_logging(settings)

    async def run() -> int:
        container = AppContainer(settings)
        try:
            report = await seed_demo_data(
                container, kb_dir=Path(args.kb_dir), credentials_path=Path(args.credentials)
            )
        finally:
            await container.close()
        if not report.created:
            print("database already contains users; nothing seeded")
            return 0
        print(f"seeded: {report.counts}")
        print(f"demo credentials written to {report.credentials_file} (local file, owner-only)")
        return 0

    return asyncio.run(run())


def cmd_index_kb(args: argparse.Namespace) -> int:
    from aegis.bootstrap import AppContainer, RequestServices  # noqa: PLC0415
    from aegis.workers.runner import run_iteration  # noqa: PLC0415

    settings = load_settings()
    _configure_logging(settings)

    async def run() -> int:
        container = AppContainer(settings)
        try:
            await container.startup()
            if args.rebuild:
                # Fills an empty collection (e.g. a new AEGIS_QDRANT_COLLECTION after changing the
                # embedding model) with every indexed document. Stop the worker while this runs.
                async with container.sessionmaker() as session:
                    rebuilt = await RequestServices(container, session).knowledge.reconcile_index()
                print(f"rebuilt index: {rebuilt} documents")
            stats = await run_iteration(container, maintenance=False)
        finally:
            await container.close()
        print(f"indexed documents: {stats.get('indexed', 0)}")
        return 0

    return asyncio.run(run())


def cmd_create_admin(args: argparse.Namespace) -> int:
    from pydantic import ValidationError  # noqa: PLC0415
    from sqlalchemy.exc import IntegrityError  # noqa: PLC0415

    from aegis.bootstrap import AppContainer  # noqa: PLC0415
    from aegis.core.time import utc_now  # noqa: PLC0415
    from aegis.domain.enums import AuditOutcome, Role  # noqa: PLC0415
    from aegis.models import User  # noqa: PLC0415
    from aegis.schemas.admin import UserCreate  # noqa: PLC0415
    from aegis.security.passwords import password_policy_problems  # noqa: PLC0415

    settings = load_settings()
    password = os.environ.get("AEGIS_BOOTSTRAP_ADMIN_PASSWORD") or getpass.getpass("Password: ")
    try:
        request = UserCreate(
            email=args.email, display_name=args.name, role=Role.ADMIN, password=password
        )
    except ValidationError as exc:
        # Name the invalid fields only - never echo the submitted values (the password).
        fields = sorted({str(error["loc"][0]) for error in exc.errors() if error.get("loc")})
        print("invalid input: " + ", ".join(fields), file=sys.stderr)
        return 1
    email = str(request.email).strip().lower()
    problems = password_policy_problems(
        password, min_length=settings.password_min_length, email=email
    )
    if problems:
        print("password rejected: " + "; ".join(problems), file=sys.stderr)
        return 1

    async def run() -> int:
        container = AppContainer(settings)
        try:
            user = User(
                email=email,
                password_hash=await container.hasher.hash_async(password),
                role=Role.ADMIN,
                display_name=request.display_name.strip(),
                customer_id=None,
                password_changed_at=utc_now(),
            )
            async with container.sessionmaker() as session:
                session.add(user)
                try:
                    await session.commit()
                except IntegrityError:
                    print(f"an account with the email {email} already exists", file=sys.stderr)
                    return 1
            await container.audit.record(
                "admin.user_create",
                outcome=AuditOutcome.SUCCESS,
                actor_role="cli",
                resource_type="user",
                resource_id=user.id,
                details={"role": Role.ADMIN.value, "via": "cli"},
            )
        finally:
            await container.close()
        print(f"administrator {email} created")
        return 0

    return asyncio.run(run())


def encrypted_columns() -> dict[type, tuple[str, ...]]:
    """Every mapped attribute stored with :class:`EncryptedText`, discovered from the models."""
    import aegis.models  # noqa: F401, PLC0415 - registers every mapper
    from aegis.db.base import Base, EncryptedText  # noqa: PLC0415

    found: dict[type, tuple[str, ...]] = {}
    for mapper in Base.registry.mappers:
        names = tuple(
            attr.key
            for attr in mapper.column_attrs
            if any(isinstance(column.type, EncryptedText) for column in attr.columns)
        )
        if names:
            found[mapper.class_] = names
    return found


ROTATION_BATCH_SIZE = 500


def cmd_rotate_encryption(_: argparse.Namespace) -> int:
    from sqlalchemy import Select, select  # noqa: PLC0415
    from sqlalchemy.orm.attributes import flag_modified  # noqa: PLC0415

    from aegis.bootstrap import AppContainer  # noqa: PLC0415

    settings = load_settings()

    async def run() -> int:
        container = AppContainer(settings)
        rotated = 0
        try:
            for model, fields in encrypted_columns().items():
                primary_key: Any = model.id  # type: ignore[attr-defined]
                last_id: Any = None
                while True:  # keyset pagination: bounded memory, one short transaction per batch
                    query: Select[Any] = (
                        select(model).order_by(primary_key).limit(ROTATION_BATCH_SIZE)
                    )
                    if last_id is not None:
                        query = query.where(primary_key > last_id)
                    async with container.sessionmaker() as session:
                        # FOR UPDATE (PostgreSQL) so a concurrent write cannot be overwritten
                        # with the value read here.
                        rows: list[Any] = list(
                            (await session.execute(query.with_for_update())).scalars()
                        )
                        if not rows:
                            break
                        for row in rows:
                            for name in fields:
                                if getattr(row, name) is not None:
                                    # Values were decrypted with whichever key matched; marking
                                    # them dirty re-encrypts them with the primary (first) key.
                                    flag_modified(row, name)
                                    rotated += 1
                        last_id = rows[-1].id
                        await session.commit()
        finally:
            await container.close()
        print(f"re-encrypted {rotated} values with the primary key")
        return 0

    return asyncio.run(run())


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="aegis", description="AegisSupport AI management commands"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    serve = sub.add_parser("serve", help="run the API server")
    serve.add_argument("--host", default="127.0.0.1")
    serve.add_argument("--port", type=int, default=8000)
    serve.set_defaults(func=cmd_serve)

    worker = sub.add_parser("worker", help="run the background worker")
    worker.add_argument("--once", action="store_true", help="run a single iteration and exit")
    worker.set_defaults(func=cmd_worker)

    sub.add_parser("migrate", help="apply database migrations").set_defaults(func=cmd_migrate)

    seed = sub.add_parser("seed", help="load demo data (development only)")
    seed.add_argument("--kb-dir", default="data/knowledge_base")
    seed.add_argument("--credentials", default="var/seed-credentials.json")
    seed.set_defaults(func=cmd_seed)

    index_kb = sub.add_parser("index-kb", help="index pending knowledge documents")
    index_kb.add_argument(
        "--rebuild",
        action="store_true",
        help="if the collection is empty, re-index every indexed document into it",
    )
    index_kb.set_defaults(func=cmd_index_kb)

    admin = sub.add_parser("create-admin", help="create an administrator account")
    admin.add_argument("--email", required=True)
    admin.add_argument("--name", default="Administrator")
    admin.set_defaults(func=cmd_create_admin)

    sub.add_parser("generate-secrets", help="print fresh random secrets").set_defaults(
        func=cmd_generate_secrets
    )

    init_env = sub.add_parser("init-env", help="write a .env file with fresh secrets")
    init_env.add_argument("--path", default=".env")
    init_env.add_argument("--force", action="store_true", help="overwrite an existing file")
    init_env.add_argument(
        "--docker", action="store_true", help="write the variables docker-compose.yml needs"
    )
    init_env.set_defaults(func=cmd_init_env)

    sub.add_parser("rotate-encryption", help="re-encrypt data with the primary key").set_defaults(
        func=cmd_rotate_encryption
    )
    sub.add_parser("check-config", help="validate configuration").set_defaults(
        func=cmd_check_config
    )

    health = sub.add_parser("healthcheck", help="container health probe")
    health.add_argument("--port", type=int, default=8000)
    health.add_argument("--worker", action="store_true", help="check the worker heartbeat file")
    health.add_argument(
        "--max-age", type=float, default=300.0, help="maximum heartbeat age in seconds"
    )
    health.set_defaults(func=cmd_healthcheck)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
